Attempt JS object structure bonus for stopwatch
Getting "uncaught TypeError: this.display is not a function" at line 16 and
it is probably some messed up context or misused/unused bind(this)